spring:
    datasource:
        url: jdbc:mysql://kgu.cgob6nkrqeo4.ap-northeast-2.rds.amazonaws.com:3306/map
        username: root
        password: rjsgml33
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false


