spring:
  datasource:
    url: jdbc:mysql://localhost:3306/map
    username: root
    password: rjsgml33
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  config:
    activate:
      on-profile: dev


